/**
 * TheAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AdminAction = 'IsPinned' | 'IsEssence' | 'Remove';

export const AdminAction = {
    IsPinned: 'IsPinned' as AdminAction,
    IsEssence: 'IsEssence' as AdminAction,
    Remove: 'Remove' as AdminAction
};

