/**
 * TheAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateTopicModel { 
    /**
     * true：小组；false：话题
     */
    isGroup: boolean;
    /**
     * 名称
     */
    name: string;
    /**
     * 简介
     */
    description: string;
    /**
     * 关联的作品。如果无关联的作品，则为null。
     */
    relatedWork?: string | null;
}

