/**
 * TheAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCommentModel { 
    /**
     * 作品Id
     */
    workId: string;
    /**
     * 评论的标题
     */
    title: string;
    /**
     * 评论的正文
     */
    text: string;
    /**
     * 打分
     */
    rating: number;
}

