/**
 * TheAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminAction } from './adminAction';


export interface DoAdminModel { 
    /**
     * 帖子id
     */
    postId?: string | null;
    action?: AdminAction;
    /**
     * 状态值。例如Action=IsPinned, Status=false，就意味着对帖子【取消精华】。
     */
    status?: boolean;
}

