/**
 * TheAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 这是一个通用的返回结构，用于返回生成的实体的id。  返回id对于前端后续的操作来说很有方便。  例如，我发送了评论，那么就会返回评论的id。
 */
export interface IdResponse { 
    id?: string;
}

