/**
 * TheAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QUser } from './qUser';
import { RequestStatus } from './requestStatus';


export interface QAdminRequest { 
    id?: string;
    topicId?: string;
    senderId?: string;
    text?: string | null;
    status?: RequestStatus;
    user?: QUser;
}

