/**
 * TheAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QTopic { 
    id?: string;
    isGroup?: boolean;
    name?: string | null;
    description?: string | null;
    relatedWork?: string | null;
    memberCount?: number;
}

