/**
 * TheAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkType } from './workType';


export interface QWork { 
    id?: string;
    /**
     * 作品名称
     */
    name?: string | null;
    /**
     * 作者
     */
    author?: string | null;
    /**
     * 描述
     */
    description?: string | null;
    type?: WorkType;
}

