/**
 * TheAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RequestStatus = 'Unhandled' | 'Accepted' | 'Refused';

export const RequestStatus = {
    Unhandled: 'Unhandled' as RequestStatus,
    Accepted: 'Accepted' as RequestStatus,
    Refused: 'Refused' as RequestStatus
};

